FROM microsoft/dotnet:latest

RUN apt-get update && apt-get -y install sqlite3 libsqlite3-dev

COPY . /app

WORKDIR /app

RUN ["dotnet", "restore", "CoreCRM.IntegrationTest"]

ENTRYPOINT ["dotnet", "test", "CoreCRM.IntegrationTest"]
